version: '3.8'

services:
  jenkins:
    # Imagem oficial com Java 17 (que funciona bem)
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped

    # Portas
    ports:
      - "8080:8080"
      - "50000:50000"

    # Volumes
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro

    # Variáveis de ambiente
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Xmx2048m -Xms1024m

    user: root

    networks:
      - jenkins_network

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins_network:
    driver: bridge